from enum import Enum

class CommonQuestionTopic(Enum):
    GENERAL_USAGE = 1
    COMMON_PROBLEMS = 2
    DEALING_WITH_MULTIPLE_OLDER_KERNELS_IN_BOOT_MENU = 3
    UPGRADING_TO_A_NEW_RELEASE = 4
    TROUBLESHOOTING = 5
    DATABASES = 6

class GeneralUsage(Enum):
    INSTALLING_SKYPE = 1
    INSTALLING_JAVA = 2
    INSTALLING_REQUIRED_PACKAGES_TO_PLAY_MOVIES_AND_MUSIC = 3

class CommonProblems(Enum):
    HOWTO_RESOLVE_ISSUES_FOR_VMWORKSTATION_AND_VMPLAYER_ON_ANY_KERNEL_AND_VERSION = 1
    HOW_CAN_I_EXCLUDE_SELECTED_PACKAGES_WHEN_I_RUN_DNF_UPDATE_COMMAND = 2
    HOWTO_CANNOT_OPEN_ACCESS_TO_CONSOLE_THE_ROOT_ACCOUNT_IS_LOCKED_IN_EMERGENCY_MODE_DRACUT_EMERGENCY_SHELL = 3

class DealingWithMultipleOlderKernelsInBootMenu(Enum):
    OLD_KERNELS_REMOVAL = 1
    OLD_KERNELS_ACCUMULATE = 2

class UpgradingToANewRelease(Enum):
    UPGRADING_TO_A_NEW_RELEASE_OF_FEDORA = 1
    UPGRADING_FEDORA_USING_THE_DNF_SYSTEM_UPGRADE = 2

class Troubleshooting(Enum):
    FIND_DISCUSSION_ABOUT_YOUR_PROBLEM = 1
    VIEWING_LOGS_ON_FEDORA = 2
    REPORT_A_BUG = 3

class Databases(Enum):
    INSTALLING_CONFIGURING_AND_TROUBLESHOOTING_MYSQL_MARIADB = 1
    POSTGRESQL = 2

class InstallingSkype(Enum):
    INSTALLING_SKYPE_RPM_REPOSITORY = 1
    INSTALLING_SKYPE_FLATPACK = 2

class InstallingJava(Enum):
    INSTALLING_OPENJDK_FOR_DEVELOPMENT = 1
    INSTALLING_ORACLE_JAVA_SE = 2
    SWITCHING_BETWEEN_JAVA_VERSION = 3
    JDK_REFERENCE = 4
    
class VMwareWhatIsIt(Enum):
    INSTALLATION = 1
    RESOLVING_CONFLICT_WITH_KERNEL = 2
    PREREQUISITE = 3
    DEAL_WITH_KERNEL_UPDATES = 4

# class ExcludingPackagesFromTransactions(Enum):

